name: bondhu_social
description: "বন্ধু সোশ্যাল - Social Media App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ==========================================================
  # FIREBASE
  # ==========================================================

  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # ==========================================================
  # GOOGLE SIGN IN
  # ==========================================================

  google_sign_in: ^7.1.1

  # ==========================================================
  # GOOGLE MOBILE ADS
  # ==========================================================

  google_mobile_ads: ^7.0.0

  # ==========================================================
  # STATE MANAGEMENT
  # ==========================================================

  provider: ^6.1.5+1

  # ==========================================================
  # IMAGE
  # ==========================================================

  image_picker: ^1.2.1
  cached_network_image: ^3.4.1

  # ==========================================================
  # OTHER
  # ==========================================================

  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
